FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy root package.json and workspace configuration
COPY package*.json ./

# Copy the apps folder
COPY apps/api/package.json ./apps/api/
COPY apps/mobile/package.json ./apps/mobile/

# Install dependencies for all workspaces
RUN npm install

# Copy all source files
COPY . .

# Build the mobile app for web
RUN npm --workspace apps/mobile run build:web

# Set environment variables for production
ENV NODE_ENV=production

# Expose build args as runtime environment variables
ARG EXPO_PUBLIC_SUPABASE_URL
ARG EXPO_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG OPENCLAW_BASE_URL
ARG OPENCLAW_API_KEY
ARG OPENCLAW_TIMEOUT_MS
ARG OPENCLAW_RETRY_ATTEMPTS
ARG APP_ENV
ARG PORT
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_ENDPOINT
ARG R2_BUCKET_NAME
ARG R2_PUBLIC_URL

ENV EXPO_PUBLIC_SUPABASE_URL=$EXPO_PUBLIC_SUPABASE_URL
ENV EXPO_PUBLIC_SUPABASE_ANON_KEY=$EXPO_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV OPENCLAW_BASE_URL=$OPENCLAW_BASE_URL
ENV OPENCLAW_API_KEY=$OPENCLAW_API_KEY
ENV OPENCLAW_TIMEOUT_MS=$OPENCLAW_TIMEOUT_MS
ENV OPENCLAW_RETRY_ATTEMPTS=$OPENCLAW_RETRY_ATTEMPTS
ENV APP_ENV=$APP_ENV
ENV PORT=${PORT:-3334}
ENV R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
ENV R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
ENV R2_ENDPOINT=$R2_ENDPOINT
ENV R2_BUCKET_NAME=$R2_BUCKET_NAME
ENV R2_PUBLIC_URL=$R2_PUBLIC_URL

# Porta da API (deve coincidir com a variável PORT)
EXPOSE 3334

# Start the API using the newly created start script
CMD ["npm", "--workspace", "apps/api", "run", "start"]
