FROM node:22-alpine AS builder

WORKDIR /app

# Instalar dependências globais se necessário
COPY package*.json ./
COPY apps/mobile/package.json ./apps/mobile/

# Instalação
RUN npm install

# Copia os arquivos
COPY . .

# Build do frontend web
RUN npm --workspace apps/mobile run build:web

# Etapa 2: Nginx para servir arquivos estáticos
FROM nginx:alpine

# Copiar os arquivos gerados no build do Expo Web para a pasta do Nginx
COPY --from=builder /app/apps/mobile/dist /usr/share/nginx/html

# Configuração simples do Nginx para SPA (React Router)
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
